// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://besatfchjxcxwpnwfbwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlc2F0ZmNoanhjeHdwbndmYndvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MjQwNjYsImV4cCI6MjA1NTEwMDA2Nn0.AC0egrIHDLwj21J7i-6Mz936uzZ9ijgjYtipykkN2n0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);